package com.seniru.tfm_mytribe;

import java.awt.FlowLayout;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;

/**
 *
 * @author Seniru
 */
public class MemberPanel extends javax.swing.JPanel {

    MemberInfoUI info;
    Member member;
    
    /**
     * Creates a panel that holds member data
     * @param member The member to be displayed
     */
    public MemberPanel(Member member) {
        this.member = member;
        initComponents();
        mGender.setText(member.getGender());
        mJoin.setText(member.getJoinDate().toString());
        mName.setText(member.name);
        mTitle.setText(member.getTitle());
        try {
            pfp.setIcon(new ImageIcon(new URL(member.getPfp())));
        } catch (MalformedURLException ex) {
            // do nothing
        }
        info = new MemberInfoUI(member);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pfp = new javax.swing.JLabel();
        mName = new javax.swing.JLabel();
        mTitle = new javax.swing.JLabel();
        mGender = new javax.swing.JLabel();
        mJoin = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(530, 0));
        setPreferredSize(new java.awt.Dimension(530, 80));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        pfp.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mName.setText("Name");

        mTitle.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mTitle.setText("Title");

        mGender.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mGender.setText("None");

        mJoin.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mJoin.setText("Joined on:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pfp, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mName, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mGender))
                    .addComponent(mJoin)
                    .addComponent(mTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pfp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mGender)
                            .addComponent(mName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mJoin)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        try {
            var hist = new HistoryManager();
        var histProc = new HistoryProcessor();
        hist.searchLogs("", "changé le rang de " + member.name , "FR", hist.searchLogs("", member.name, "FR", "default")).forEach(x -> {            
        });
        } catch (Exception ex) {
            Logger.getLogger(MemberPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
                this.info.setVisible(true);
         
    }//GEN-LAST:event_formMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel mGender;
    private javax.swing.JLabel mJoin;
    private javax.swing.JLabel mName;
    private javax.swing.JLabel mTitle;
    private javax.swing.JLabel pfp;
    // End of variables declaration//GEN-END:variables
}
